#!/usr/bin/env bash
# Run on openclawpc after pipeline completes.
# Rsyncs pipeline output JSON to Mac Studio, then triggers
# regeneration + commit on the Mac side.
#
# Prerequisites on openclawpc:
#   - SSH key in ~/.ssh/authorized_keys on macstudio
#   - Tailscale up (or LAN reachability of macstudio.local)
#
# Usage:
#   ./pipeline/sync/sync_to_macstudio.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
MAC_HOST="${PARISCOMEDY_MAC_HOST:-macstudio.local}"
MAC_USER="${PARISCOMEDY_MAC_USER:-chuck}"
MAC_REPO="${PARISCOMEDY_MAC_REPO:-/Users/chuck/Documents/Claude/Projects/pariscomedy.com/_repo}"
RSYNC_FLAGS="-avz --checksum"
BACKUP_DIR="${REPO_ROOT}/pipeline/output/backups/$(date +%Y%m%d_%H%M%S)"

log() { echo "[$(date +%H:%M:%S)] [SYNC] $*"; }

# Safety: confirm host is reachable before touching anything
log "Checking reachability of ${MAC_HOST}..."
if ! ssh -o ConnectTimeout=5 -o BatchMode=yes "${MAC_USER}@${MAC_HOST}" true 2>/dev/null; then
  log "ERROR: Cannot reach ${MAC_USER}@${MAC_HOST} — aborting sync."
  exit 1
fi

# Safety: confirm target repo path exists on Mac
if ! ssh "${MAC_USER}@${MAC_HOST}" "test -d '${MAC_REPO}/data'" 2>/dev/null; then
  log "ERROR: Target path ${MAC_REPO}/data does not exist on Mac Studio — aborting."
  exit 1
fi

# Safety: local backup of what's currently on Mac before overwriting
log "Creating backup of Mac Studio data before sync..."
mkdir -p "$BACKUP_DIR"
rsync -avz --checksum \
  "${MAC_USER}@${MAC_HOST}:${MAC_REPO}/data/shows.json" \
  "${MAC_USER}@${MAC_HOST}:${MAC_REPO}/data/shows_generated.json" \
  "${MAC_USER}@${MAC_HOST}:${MAC_REPO}/pipeline/output/review_queue.json" \
  "$BACKUP_DIR/" 2>/dev/null || log "Warning: backup partially failed (continuing)"
log "Backup saved to $BACKUP_DIR"

log "Pushing pipeline output to ${MAC_USER}@${MAC_HOST}:${MAC_REPO}"

# Sync review_queue.json (the committed file for the admin UI)
rsync $RSYNC_FLAGS \
  "$REPO_ROOT/pipeline/output/review_queue.json" \
  "${MAC_USER}@${MAC_HOST}:${MAC_REPO}/pipeline/output/review_queue.json"

# Sync updated shows.json (merged in stage 07)
rsync $RSYNC_FLAGS \
  "$REPO_ROOT/data/shows.json" \
  "${MAC_USER}@${MAC_HOST}:${MAC_REPO}/data/shows.json"

# Sync shows_generated.json (regenerated by stage 07)
rsync $RSYNC_FLAGS \
  "$REPO_ROOT/data/shows_generated.json" \
  "${MAC_USER}@${MAC_HOST}:${MAC_REPO}/data/shows_generated.json"

log "Sync complete. Triggering Mac Studio regeneration..."

ssh "${MAC_USER}@${MAC_HOST}" \
  "cd '${MAC_REPO}' && bash pipeline/sync/receive_on_mac.sh"

log "Done — Mac Studio updated and pushed."
